name: Daily Repository Update

on:
  schedule:
    # triggers at 2:50 AM IST (which is 9:20 PM UTC)
    - cron: '20 21 * * *'   # Triggers at 9:20 PM UTC (2:50 AM IST)

permissions:
  contents: write # allows pushing changes to the repository

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository
      - name: checkout code
        uses: actions/checkout@v2

      # take pull of latest codebase 
      - name: take latest pull
        id: pull
        run: |
          echo "taking latest pull"
          git pull origin master 

      # randomly choose the number of pushes (0, 1, or 2)
      - name: choose number of pushes
        id: pushes
        run: |
          # randomly choose the number of pushes (0, 1, or 2)
          PUSH_COUNT=$((RANDOM % 3))
          echo "selected number of pushes: $PUSH_COUNT"
          echo "::set-output name=push_count::$PUSH_COUNT"

      # set up git user
      - name: set git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # clear the update_log.md file before making changes
      - name: clear update_log.md file
        run: |
          echo "" > update_log.md
          echo "cleared update_log.md before updating" # just for logging purposes

      # make repository changes and push at the selected times
      - name: make repository changes
        run: |
          # iterate over the selected number of pushes
          for i in $(seq 1 ${{ steps.pushes.outputs.push_count }}); do
            echo "# auto-updated at $(date)" >> update_log.md
            git add update_log.md
            git commit -m "chore: update at $(date)"
            git push
          done
