name: Daily Update

on:
  push:
    branches:
      - master
  schedule:
    # triggers at 2:50 AM IST (9:20 PM UTC)
    - cron: '20 21 * * *'

permissions:
  contents: write
  pull-requests: write # crucial for creating PRs

jobs:
  update_master:
    runs-on: ubuntu-latest
    steps:
      # Step 1: checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: set up Git user using GitHub secrets
      - name: Set git user
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"

      # Step 3: fetch latest changes 
      - name: Fetch latest changes
        run: git fetch origin master

      # Step 4: checkout to master branch 
      - name: Checkout master branch
        run: git checkout master

      # Step 5: add current IST and UTC time in update_log.md file  
      - name: Update update_log.md
        run: |
          echo "" > update_log.md  # Clear previous content
          echo "# auto-updated at $(TZ='Asia/Kolkata' date +'%Y-%m-%d %H:%M:%S IST')" >> update_log.md
          echo "# auto-updated at $(TZ='UTC' date +'%Y-%m-%d %H:%M:%S UTC')" >> update_log.md

      # Step 6: add update_log.md file and commit it  
      - name: Add and commit changes
        run: |
          git add update_log.md
          git commit -m "Corrected typo in error message for invalid password"

      # Step 7: push the latest changes
      - name: Push changes to master
        run: git push origin master
