name: Daily Run

on:
  push:
    branches:
      - master
  schedule:
    # triggers at 2:50 AM IST (9:20 PM UTC)
    - cron: '20 21 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  commit-to-master:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Git user configuration
      - name: Set git user
        run: |
          git config --global user.name "ankitpakhale"
          git config --global user.email "akp3067@gmail.com"

      # Step 3: Ensure we are on the master branch and pull the latest changes
      - name: Checkout master and pull latest
        run: |
          git checkout master
          git pull origin master

      # Step 4: Create or switch to the update branch
      - name: Create and switch to update branch
        run: |
          git checkout -B update-branch

      # Step 5: Attempt to rebase and resolve conflicts
      - name: Rebase update branch with master
        run: |
          git fetch origin master
          git rebase origin/master || git rebase --abort

      # Step 6: Resolve conflicts using 'ours' strategy (if any)
      - name: Resolve conflicts automatically
        run: |
          git merge -X ours origin/master || true

      # Step 7: Update the file (simulate a contribution)
      - name: Update update_log.md
        run: |
          echo "" > update_log.md
          echo "# auto-updated at $(TZ='Asia/Kolkata' date +'%Y-%m-%d %H:%M:%S')" >> update_log.md

      # Step 8: Add, commit, and push changes
      - name: Commit and push changes
        run: |
          git add update_log.md
          git commit -m "chore: auto update at $(TZ='Asia/Kolkata' date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin update-branch --force

      # Step 9: Create a pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Auto-update at $(TZ='Asia/Kolkata' date +'%Y-%m-%d %H:%M:%S')"
          body: "Automated commit to update the log file"
          base: master
          branch: update-branch
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[create-pull-request] automated change"
          committer: GitHub <noreply@github.com>
          author: ankitpakhale <ankitpakhale@users.noreply.github.com>
          signoff: false
          delete-branch: false
          draft: false
