name: Daily Run

on:
  push:
    branches:
      - master
  schedule:
    # triggers at 2:50 AM IST (which is 9:20 PM UTC)
    - cron: '20 21 * * *'

permissions:
  contents: write  # allows pushing changes to the repository
  pull-requests: write  # allows creating and merging prs

jobs:
  commit-to-master:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Git user configuration
      - name: Set git user
        run: |
          git config --global user.name "ankitpakhale"
          git config --global user.email "akp3067@gmail.com"

      # Step 3: Ensure we are on the master branch and update it
      - name: Checkout master and pull latest
        run: |
          git checkout master
          git pull origin master

      # Step 4: Create a new branch (if necessary)
      - name: Create and switch to update branch
        run: |
          git checkout -b update-branch

      # Step 5: Pull the latest changes from the update branch (with rebase to avoid merge conflicts)
      - name: Pull changes from update-branch
        run: |
          git pull origin update-branch --rebase || true # Use '|| true' to prevent failure on conflicts

      # Step 6: Update the file (automatically edit the file to simulate a contribution)
      - name: Update update_log.md
        run: |
          echo "" > update_log.md
          echo "# auto-updated at $(TZ='Asia/Kolkata' date +'%Y-%m-%d %H:%M:%S')" >> update_log.md

      # Step 7: Add, commit, and push changes
      - name: Commit and push changes
        run: |
          git add update_log.md
          git commit -m "chore: auto update at $(TZ='Asia/Kolkata' date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin update-branch || echo "Failed to push"

      # Step 8: Create a pull request (optional, if you want to use PRs to trigger contributions)
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Auto-update at $(TZ='Asia/Kolkata' date +'%Y-%m-%d %H:%M:%S')"
          body: "Automated commit to update the log file"
          head: update-branch
          base: master
